added conditional code to choose what disk to check
statisticsnorway/ssb-project-cli pull request #332
Opened 2023-09-19 13:26 UTC by ssb-jnk

This PR solves the problem where we check the wrong disk for diskspace while ssb-project is running on-prem.

Ref: https://ssb-norge.slack.com/archives/C015E7B4YS0/p1695126307603229?thread_ts=1695044075.952239&cid=C015E7B4YS0

2023-09-19 13:31 UTC, ssb-jnk commented
Awaiting review from @mmwinther

2023-09-20 06:56 UTC, mmwinther requested changes

2023-09-20 06:56 UTC, mmwinther commented on src/ssb_project_cli/ssb_project/create/create.py
> +            psutil.disk_usage("/home/jovyan/")
Make this repeated string a constant.

2023-09-20 07:09 UTC, mmwinther approved these changes
Nice fix 👍

2023-09-20 07:12 UTC, merged